TrajectoryPlannerROS:
    acc_lim_x: 8.0
    acc_lim_y: 0.0
    acc_lim_theta: 4.0

    max_vel_x: 2.0
    min_vel_x: 0.1

    max_vel_theta: 1.0
    min_vel_theta: -1.0
    min_in_place_vel_theta: 0.20

    sim_time: 1.0
    sim_granularity: 0.025

    pdist_scale: 2.0
    gdist_scale: 0.8
    occdist_scale: 0.01

    oscillation_reset_dist: 0.05
    escape_reset_dist: 0.10
    escape_reset_theta: 1.7

    vx_samples: 10
    vtheta_samples: 20

    heading_lookahead: 0.5

    holonomic_robot: false

    escape_vel: -0.3

    dwa: true

    heading_scoring: true
    heading_scoring_timestep: 0.5

    simple_attractor: false
    angular_sim_granularity: 0.025

    yaw_goal_tolerance: 0.25
    xy_goal_tolerance: 0.5
    latch_xy_goal_tolerance: true
