TrajectoryPlannerROS:
    max_vel_x: 1.0
    min_vel_x: 0.3
    max_rotational_vel: 0.4
    min_in_place_rotational_vel: 0.15
    escape_vel: -0.3

    acc_lim_th: 5.0
    acc_lim_x: 4.0
    acc_lim_y: 0.0

    yaw_goal_tolerance: 0.4
    xy_goal_tolerance: 0.2
    latch_xy_goal_tolerance: false

    sim_time: 3.0
    sim_granularity: 0.025
    angular_sim_granularity: 0.025
    vx_samples: 5 # Default 3, 8-15 for high speed comupters
    vtheta_samples: 20
    controller_frequency: 10

    meter_scoring: false
    path_distance_bias: 0.6
    goal_distance_bias: 0.8
    occdist_scale: 0.01

    heading_scoring: true
    heading_scoring_timestep: 0.2
    heading_lookahead: 0.325

    dwa: true
    holonomic_robot: false
    publish_cost_grid_pc: true
