obstacle_range: 4.5
raytrace_range: 5.0
footprint: [[-0.20, 0.39], [0.94, 0.39], [0.94, -0.39], [-0.20, -0.39]]
inflation_radius: 0.55

transform_tolerance: 0.2 # Max running just hardware nodes is ~0.0006 secs according to tf_monitor

observation_sources: hokuyo_laser_scan_sensor

hokuyo_laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan,
                           marking: true, clearing: true,  expected_update_rate: 0.133}

# LRf @ 15Hz so 7.5Hz for update rate
