base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

controller_frequency: 25.0
planner_patience: 5.0
controller_patience: 15.0

conservative_reset_dist: 0.1
