NavfnROS: {default_tolerance: 0.1, visualize_potential: true}
TrajectoryPlannerROS: {acc_lim_theta: 4.0, acc_lim_x: 8.0, acc_lim_y: 0.0, angular_sim_granularity: 0.025,
  dwa: true, escape_reset_dist: 0.1, escape_reset_theta: 1.7, escape_vel: -0.3, gdist_scale: 0.8,
  heading_lookahead: 0.5, heading_scoring: true, heading_scoring_timestep: 0.5, holonomic_robot: false,
  latch_xy_goal_tolerance: true, max_vel_theta: 1.0, max_vel_x: 2.0, min_in_place_vel_theta: 0.3,
  min_vel_theta: 0.0, min_vel_x: 0.1, occdist_scale: 0.01, oscillation_reset_dist: 0.05,
  pdist_scale: 2.0, restore_defaults: false, sim_granularity: 0.025, sim_time: 1.0,
  simple_attractor: false, vtheta_samples: 20, vx_samples: 10, xy_goal_tolerance: 0.5,
  y_vels: '-0.3,-0.1,0.1,-0.3', yaw_goal_tolerance: 0.25}
aggressive_reset: {reset_distance: 1.84}
base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS
clearing_rotation_allowed: true
conservative_reset: {reset_distance: 3.0}
conservative_reset_dist: 3.0
controller_frequency: 25.0
controller_patience: 15.0
global_costmap:
  cost_scaling_factor: 10.0
  footprint: '[[-0.21,0.4],[0.95,0.4],[0.95,-0.4],[-0.21,-0.4]]'
  global_frame: odom
  height: 10
  hokuyo_laser_scan_sensor: {clearing: true, data_type: LaserScan, expected_update_rate: 0.2,
    marking: true, sensor_frame: laser, topic: scan}
  inflation_radius: 0.55
  lethal_cost_threshold: 100
  map_topic: map
  map_type: costmap
  mark_threshold: 0
  max_obstacle_height: 2.0
  max_obstacle_range: 2.5
  observation_sources: hokuyo_laser_scan_sensor
  obstacle_range: 2.5
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  publish_frequency: 0.0
  publish_voxel_map: false
  raytrace_range: 3.5
  resolution: 0.05
  restore_defaults: false
  robot_base_frame: base_footprint
  robot_radius: 0.46
  rolling_window: false
  static_map: true
  track_unknown_space: false
  transform_tolerance: 1.0
  unknown_cost_value: 0
  unknown_threshold: 15
  update_frequency: 5.0
  width: 0
  z_resolution: 0.2
  z_voxels: 10
local_costmap:
  cost_scaling_factor: 10.0
  footprint: '[[-0.21,0.4],[0.95,0.4],[0.95,-0.4],[-0.21,-0.4]]'
  global_frame: odom
  height: 6
  hokuyo_laser_scan_sensor: {clearing: true, data_type: LaserScan, expected_update_rate: 0.2,
    marking: true, sensor_frame: laser, topic: scan}
  inflation_radius: 0.55
  lethal_cost_threshold: 100
  map_topic: map
  map_type: costmap
  mark_threshold: 0
  max_obstacle_height: 2.0
  max_obstacle_range: 2.5
  observation_sources: hokuyo_laser_scan_sensor
  obstacle_range: 2.5
  origin_x: 0.0
  origin_y: 0.0
  origin_z: 0.0
  publish_frequency: 2.0
  publish_voxel_map: false
  raytrace_range: 3.5
  resolution: 0.05
  restore_defaults: false
  robot_base_frame: base_footprint
  robot_radius: 0.46
  rolling_window: true
  static_map: false
  track_unknown_space: false
  transform_tolerance: 1.0
  unknown_cost_value: 0
  unknown_threshold: 15
  update_frequency: 5.0
  width: 6
  z_resolution: 0.2
  z_voxels: 10
oscillation_distance: 0.5
oscillation_timeout: 0.0
planner_frequency: 0.0
planner_patience: 5.0
recovery_behavior_enabled: true
restore_defaults: false
shutdown_costmaps: false
